sudo: required
language: node_js
services:
  - docker
node_js:
- 8
cache:
  directories:
    - node_modules
env:
  - CI=true

before_install:
  - docker build -t ryanb/docker-react -f Dockerfile.dev .

script:
  - docker run ryanb/docker-react npm run test -- --coverage